### ISSUE TITLE
Will there be Dragon Quest Slimes?

### ISSUE THREAD

**Issue by sour-dani** [auxpatch/John-Lemon-Final#1]
In the previous repo there was a severe lack of slime. 

# Will this one have slimes?
They are an integral part video games. My first time seeing them was in DQ8 (Dragon Quest 8).

Hopefully the [other contributors](https://yoinkysploinky.xyz/) ca n 

## Here is an example of slime.
![Baby_Slime](https://github.com/auxpatch/John-Lemon-Final/assets/35577693/9930a46c-3768-4ff1-8f4b-30fd7eeb1c63)
They come in many shapes and colors, this one is a Baby slime, not available in the main line series.

## Solution.
When implementing a new scene make sure to add a spritesheet with slimes.

![download](https://github.com/auxpatch/John-Lemon-Final/assets/35577693/d1466042-27ec-48e6-a7e6-8f373215d3bf)

here is a sprite sheet.

**Comment by auxpatch** [comment]
i hate you
